server:
  port: 5050
spring:
  application:
    name: ORDERDETAIL-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/mabase
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka