server:
  port:   6060
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mabase
    username: root
    password: 123
  application:
    name: CLIENT-SERVICE
  mail:
    host: smtp.gmail.com
    port: 587
    username: irgim.system@gmail.com
    password: jhvnfdahjgmbgtpv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

